### PR TITLE
[scummvm] Fix windows patch

### PR DESCRIPTION
**Pull request by fetzerch**
Sry .h was missing.

This alone won't do it. As always there's something broken with applying patches on windows.
I'll try to fix and PR it.

### CODE REVIEW

**Comment by fetzerch** [comment]
Related changes: https://github.com/fetzerch/xbmc/commits/cmake_patchfiles
Test build: http://jenkins.kodi.tv/job/WIN-32/10573/

**Comment by garbear** [comment]
looks like scummv built successfully on windows

**Comment by garbear** [comment]
ready to merge?

**Comment by fetzerch** [comment]
Yes :)

Am 06.11.2016 20:21 schrieb "Garrett Brown" notifications@github.com:

**Comment by garbear** [comment]
On windows I'm getting the following build error:

```
gcc  -O3 -D__LIBRETRO__ -DNONSTANDARD_PORT -DUSE_RGB_COLOR -DUSE_OSD -DDISABLE_TEXT_CONSOLE -DFRONTEND_SUPPORTS_RGB565 -Wno-multichar -DFS_TYPE_POSIX -DUSE_TREMOR -DUSE_VORBIS -DUSE_ZLIB  -DWANT_ZLIB -DENABLE_SCUMM=STATIC_PLUGIN -DENABLE_SCUMM_7_8 -DENABLE_AGI=STATIC_PLUGIN -DENABLE_AGOS=STATIC_PLUGIN -DENABLE_AGOS2 -DENABLE_BBVS=STATIC_PLUGIN -DENABLE_CINE=STATIC_PLUGIN -DENABLE_CRUISE=STATIC_PLUGIN -DENABLE_DREAMWEB=STATIC_PLUGIN -DENABLE_GOB=STATIC_PLUGIN -DENABLE_GROOVIE=STATIC_PLUGIN -DENABLE_GROOVIE2 -DENABLE_KYRA=STATIC_PLUGIN -DENABLE_LOL -DENABLE_EOB -DENABLE_LASTEXPRESS=STATIC_PLUGIN -DENABLE_LURE=STATIC_PLUGIN -DENABLE_MADE=STATIC_PLUGIN -DENABLE_MADS=STATIC_PLUGIN DENABLE_MOHAWK=STATIC_PLUGIN -DENABLE_MYST -DENABLE_RIVEN -DENABLE_NEVERHOOD=STATIC_PLUGIN -DENABLE_QUEEN=STATIC_PLUGIN -DENABLE_SAGA=STATIC_PLUGIN -DENABLE_IHNM -DENABLE_SAGA2 -DENABLE_SCI=STATIC_PLUGIN -DENABLE_SCI32 -DENABLE_SHERLOCK=STATIC_PLUGIN -DENABLE_SKY=STATIC_PLUGIN -DENABLE_SWORD1=STATIC_PLUGIN -DENABLE_SWORD2=STATIC_PLUGIN -DENABLE_TINSEL=STATIC_PLUGIN -DENABLE_TOON=STATIC_PLUGIN -DENABLE_TOUCHE=STATIC_PLUGIN -DENABLE_TSAGE=STATIC_PLUGIN -DENABLE_VOYEUR=STATIC_PLUGIN -I../../../../backends/platform/libretro -I../../../.. -I../../../../backends/platform/libretro/deps -I../../../../engines -I../../../../backends/platform/libretro/libretro-common/include -I../../../../backends/platform/libretro/libretro-common/include/compat -I../../../../backends/platform/libretro -I../../../.. -I../../../../backends/platform/libretro/deps -I../../../../engines -I../../../../backends/platform/libretro/libretro-common/include -I../../../../backends/platform/libretro/libretro-common/include/compat  -c -o ../../../../backends/platform/libretro/deps/tremor/block.o ../../../../backends/platform/libretro/deps/tremor/block.c
In file included from ../../../../backends/platform/libretro/deps/tremor/misc.h:22:0,
                 from ../../../../backends/platform/libretro/deps/tremor/block.c:27:
../../../../backends/platform/libretro/deps/tremor/tremor_shared.h:12:15: error:
 expected '=', ',', ';', 'asm' or '__attribute__' before 'int'
../../../../backends/platform/libretro/deps/tremor/tremor_shared.h:25:1: error:
unknown type name '_inline'
../../../../backends/platform/libretro/deps/tremor/tremor_shared.h:25:28: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'bitreverse'
mingw32-make.exe: *** [../../../../backends/platform/libretro/deps/tremor/block.o] Error 1
mingw32-make.exe: Leaving directory `C:/Users/garrett/Documents/kodi/project/cmake/addons/build/scummvm/src/scummvm/backends/platform/libretro/build'
NMAKE : fatal error U1077: 'call' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

I've launched a win32 jenkins instance to see if the problem occurs there as well

**Comment by fetzerch** [comment]
Can you check if the patch has been applied? Did you clean the build dir before?

**Pull request merged**
