### PR TITLE
[scummvm] Build fixes

### PR DESCRIPTION
**Pull request by fetzerch**
- Fix build in debug mode
- Use self-contained zlib (fixes build on osx)

Not sure if it compiles on windows, will try that tomorrow.

### CODE REVIEW

**Comment by garbear** [comment]
I'll run a test compile on both. yesterday windows failed before it even got to the patch part, but maybe that's just my build environment

**Comment by garbear** [comment]
Windows:

```
[ 46%] Performing update step for 'scummvm'
warning: LF will be replaced by CRLF in CMakeLists.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in backends/platform/libretro/build/Makefil
e.rej.
The file will have its original line endings in your working directory.
Current branch master is up to date.
Already up-to-date!
[ 46%] Performing configure step for 'scummvm'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/garrett/Documents/kodi/project/cma
ke/addons/build/scummvm/src/scummvm-build
[ 46%] Performing build step for 'scummvm'

Microsoft (R) Program Maintenance Utility Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[ 12%] Performing build step for 'scummvm'
process_begin: CreateProcess(NULL, uname -a, ...) failed.
mingw32-make.exe: Entering directory `C:/Users/garrett/Documents/kodi/project/cm
ake/addons/build/scummvm/src/scummvm/backends/platform/libretro/build'
mkdir -p backends/platform/libretro
The syntax of the command is incorrect.
mingw32-make.exe: *** [backends/platform/libretro/libretro.o] Error 1
mingw32-make.exe: Leaving directory `C:/Users/garrett/Documents/kodi/project/cma
ke/addons/build/scummvm/src/scummvm/backends/platform/libretro/build'
NMAKE : fatal error U1077: 'call' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by garbear** [comment]
osx works!

**Comment by fetzerch** [comment]
I'd have patches, that fix the windows build: https://github.com/fetzerch/xbmc/commit/0b97f65a2a81b965418e018e666641bf5c45a38e and https://github.com/kodi-game/game.libretro.scummvm/compare/master...fetzerch:win32. However I'm struggling to get the buildsystem to apply the 2 patches for scummvm on windows. When I manually apply them it works. Could be some issue with git and the line-endings. Could you please check what git autocrlf is set to on your build machine?

```
patching file backends/platform/libretro/build/Makefile
Hunk #1 FAILED at 164.
1 out of 1 hunk FAILED -- saving rejects to file backends/platform/libretro/build/Makefile.rej
patching file backends/platform/libretro/build/Makefile
Hunk #1 FAILED at 127.
1 out of 1 hunk FAILED -- saving rejects to file backends/platform/libretro/build/Makefile.rej
```

**Comment by garbear** [comment]
I've run into this before. The line endings are converted by git upon checkout, so the solution I found was to avoid git by downloading the tarball directly from https://github.com/libretro/scummvm/archive/master.tar.gz

**Pull request merged**
